baseurl = "/"
languageCode = "en-us"
title = "mj cowan"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "mj cowan"
	description = "Porfolio"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm MJ**, a web designer & developer<br> working on learning new things.<br>I'm interested in all things digital marketing<br> and exploring new tech."
		# The icons will be shown if you enter your username
		
		github = "CowanMedia"
		linkedin = "michellepcowan"

		copyright = [
			"&copy; MJ Cowan",
			"Design: [HTML5 UP](//html5up.net)",
			
		]


	[params.about]
		hide  = false
		title = "About Me"
		content = "I'm a newbie to web development, aiming at keeping things as simple as possible and learning how to write clean code. This portfolio site is part of a learning project, using the Hugo/NetlifyCMS static site set-up with AWS. Awesome! Loving this. Check out my current work below."

	[params.portfolio]
		hide  = false
		title = "Current Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/materialize-portfolio.jpg"
			thumb = "thumbs/materialize-portfolio.jpg"
			title = "Portfolio site using MaterializeCSS."
			description = "Shows a gallery of various coding projects"
			URL = "http://www.mjcowan.com"

		[[params.portfolio.gallery]]
			image = "fulls/gex-finalwebsite.jpg"
			thumb = "thumbs/gex-finalwebsite.jpg"
			title = "Company website. <br>Uses material design Bootstrap, JS, nunjucks.js, APIs."
			description = "Multi-page, mobile-ready responsive site for scienced-based manufacturing company. In process: single page app for document library using Firebase/ReactJS."
			URL = "https://www.gexcorp.com"

		[[params.portfolio.gallery]]
			image = "fulls/ACTonDrugs-site.jpg"
			thumb = "thumbs/ACTonDrugs-site.jpg"
			title = "Non-profit website <br>Uses WordPress, custom child theme on Genesis Framework."
			description = "Multi-page, mobile-ready responsive site for local non-profit organization."
			URL = "https://www.actondrugs.org"

		[[params.portfolio.gallery]]
			image = "fulls/avonlea-website.jpg"
			thumb = "thumbs/avonlea-website.jpg"
			title = "Small business website <br>Uses WordPress, custom theme on Genesis Framework."
			description = "Multi-page, mobile-ready responsive site for counseling service company."
			URL = "https://www.avonleacounseling.com"		


	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "I'd love to hear from you."

		# This can be exact coordinates or a searchable address in google maps
		
		address = [
			
			"Denver, Colorado",
			"United States"
		]
		
		email = "cowanmedia@gmail.com"

		[params.contact.form]

			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"



