baseurl = "/"
languageCode = "en-us"
title = "mj cowan"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "mj cowan"
	description = "Porfolio"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm MJ**, a web designer & developer<br> working on learning new things.<br>I'm interested in all things digital marketing<br> and exploring new tech."
		# The icons will be shown if you enter your username
		github = "CowanMedia"
		linkedin = "michellepcowan"

		copyright = [
			"&copy; MJ Cowan",
			"Design: [HTML5 UP](//html5up.net)",
			
		]


	[params.about]
		hide  = false
		title = "About Me"
		content = "I'm a newbie to web design and development, aiming at keeping things as simple as possible and learning how to write clean code. This portfolio site is part of a learning project, using the Hugo/NetlifyCMS static site set-up with the strata theme. Awesome! Loving this."

	[params.portfolio]
		hide  = false
		title = "Current Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/materialize-portfolio.jpg"
			thumb = "thumbs/materialize-portfolio.jpg"
			title = "Portfolio site using MaterializeCSS."
			description = "Shows a gallery of various coding projects"
			URL = "http://www.mjcowan.com"

		[[params.portfolio.gallery]]
			image = "fulls/gexcorp-site.jpg"
			thumb = "thumbs/gexcorp-site.jpg"
			title = "Company website. <br>Uses material design Bootstrap, nunjucks, apis."
			description = "Site still under development, but you can see the live test version."
			url = "https://thirsty-ardinghelli-b47326.netlify.com/"


	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "I'd love to hear from you."

		# This can be exact coordinates or a searchable address in google maps
		
		address = [
			
			"Denver, Colorado",
			"United States"
		]
		
		email = "cowanmedia@gmail.com"

		[params.contact.form]

			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
 [[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

 [[menu.main]]
  name = "About"
  url  = "about"
  weight = 5

 [[menu.main]]
  name = "Blog"
  url  = "post/"
  weight = 10
